# docker-compose.yml

version: '3.9'

services:
  app:
    build: .
    container_name: fountainai_ensemble_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TYPESENSE_API_KEY=typesense-api-key
    depends_on:
      - typesense

  typesense:
    image: typesense/typesense:0.23.1
    container_name: typesense_service
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    environment:
      - TYPESENSE_API_KEY=typesense-api-key
      - TYPESENSE_DATA_DIR=/data

volumes:
  typesense-data:
