# docker-compose.yml for FountainAI Ensemble Service

version: '3.8'

services:
  app:
    build: .
    container_name: fountainai_ensemble_service
    volumes:
      - .:/service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - typesense

  typesense:
    image: typesense/typesense:0.24.0
    container_name: typesense_service
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_API_KEY=your_typesense_api_key
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data

volumes:
  typesense_data: {}

